# Generated by Django 4.2.24 on 2026-01-07 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='meeting_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='meeting_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='meeting_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
