# Generated by Django 4.2.24 on 2026-01-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation_app', '0002_order_meeting_done_order_meeting_scheduled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
