
# Generated by Django 4.2.24 on 2025-10-25 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('automation_app', '0010_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistory',
            name='user_id',
        ),
        
   migrations.AddField(
    model_name='chathistory',
    name='user',
    field=models.ForeignKey(
        to=settings.AUTH_USER_MODEL,
        on_delete=django.db.models.deletion.CASCADE,
        null=True,
        blank=True
    ),
),
    ]
