# Generated by Django 4.2.24 on 2025-10-25 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation_app', '0012_alter_chathistory_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatHistory',
        ),
    ]
