# Generated by Django 4.2.24 on 2025-10-27 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation_app', '0015_payment_transaction_id_alter_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('ready_for_payment', 'Ready For Payment'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
