# Generated by Django 4.2.24 on 2025-11-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation_app', '0018_alter_payment_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='project_videos/'),
        ),
    ]
