# Generated by Django 4.2.24 on 2025-11-23 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation_app', '0021_alter_order_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='action',
            field=models.CharField(choices=[('create_service', 'Created a Service'), ('update_service', 'Updated a Service'), ('delete_service', 'Deleted a Service'), ('create_project', 'Created a Project'), ('update_project', 'Updated a Project'), ('delete_project', 'Deleted a Project'), ('edit_order', 'Edited an Order'), ('delete_order', 'Deleted an Order')], max_length=50),
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, max_length=150, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
