# Generated by Django 4.2.24 on 2025-11-26 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation_app', '0022_alter_activity_action_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='instagram_account_id',
            field=models.CharField(blank=True, help_text='Enter the Instagram Business/Creator Account ID', max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='InstagramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_id', models.CharField(max_length=50)),
                ('sender_id', models.CharField(max_length=50)),
                ('sender_username', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField()),
                ('reply', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InstagramComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_id', models.CharField(max_length=50)),
                ('sender_id', models.CharField(max_length=50)),
                ('sender_username', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.TextField()),
                ('reply', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instagram_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
