# Generated by Django 4.2.24 on 2025-11-26 14:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation_app', '0023_customuser_instagram_account_id_instagrammessage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramcomment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instagram_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='instagrammessage',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instagram_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
