# Generated by Django 4.2.24 on 2025-11-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation_app', '0024_alter_instagramcomment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='instagram_access_token',
            field=models.TextField(blank=True, help_text='Access token for Instagram Graph API', null=True),
        ),
    ]
