# Generated by Django 4.2.24 on 2025-12-07 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation_app', '0025_customuser_instagram_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='facebook_page_id',
            field=models.CharField(blank=True, help_text='Facebook Page ID linked to this user', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='FacebookMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(max_length=50)),
                ('sender_name', models.CharField(blank=True, max_length=100, null=True)),
                ('recipient_page_id', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('reply', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facebook_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FacebookComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=100)),
                ('sender_id', models.CharField(max_length=50)),
                ('sender_name', models.CharField(blank=True, max_length=100, null=True)),
                ('comment', models.TextField()),
                ('reply', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facebook_comments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
