# Generated by Django 4.2.24 on 2025-12-08 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation_app', '0026_customuser_facebook_page_id_facebookmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='facebook_access_token',
            field=models.TextField(blank=True, help_text='Access token for Facebook Graph API', null=True),
        ),
    ]
