# Generated by Django 4.2.24 on 2025-12-08 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation_app', '0027_customuser_facebook_access_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facebookcomment',
            old_name='post_id',
            new_name='recipient_id',
        ),
    ]
