# Generated by Django 4.2.24 on 2025-12-10 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation_app', '0028_rename_post_id_facebookcomment_recipient_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(max_length=100)),
                ('business_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat_history', models.JSONField(default=list)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_agents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
