# Generated by Django 4.2.24 on 2025-12-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation_app', '0029_businesssession'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssession',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
