# Generated by Django 4.2.24 on 2025-12-14 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation_app', '0031_agentorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSessionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('ready_for_payment', 'Ready for Payment'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='automation_app.businesssession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_session_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='AgentOrder',
        ),
    ]
