# Generated by Django 4.2.24 on 2025-12-14 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation_app', '0032_businesssessionorder_delete_agentorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesssessionorder',
            old_name='description',
            new_name='order_details',
        ),
        migrations.RemoveField(
            model_name='businesssessionorder',
            name='title',
        ),
    ]
