# Generated by Django 4.2.24 on 2025-12-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation_app', '0033_rename_description_businesssessionorder_order_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesssessionorder',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
