# Generated by Django 4.2.24 on 2025-12-16 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation_app', '0035_agentapikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='SDKChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('chat_history', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation_app.agentapikey')),
            ],
            options={
                'unique_together': {('api_key', 'session_id')},
            },
        ),
    ]
