# Generated by Django 4.2.24 on 2025-12-16 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation_app', '0036_sdkchatsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('business_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_bots', to='automation_app.businesssession')),
            ],
        ),
    ]
