# Generated by Django 4.2.24 on 2025-12-20 13:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('automation_app', '0037_telegrambot'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='facebookcomment',
            index=models.Index(fields=['recipient_id', 'timestamp'], name='automation__recipie_50858d_idx'),
        ),
        migrations.AddIndex(
            model_name='facebookmessage',
            index=models.Index(fields=['recipient_page_id', 'timestamp'], name='automation__recipie_7ef462_idx'),
        ),
        migrations.AddIndex(
            model_name='instagramcomment',
            index=models.Index(fields=['recipient_id', 'timestamp'], name='automation__recipie_f7abf8_idx'),
        ),
        migrations.AddIndex(
            model_name='instagrammessage',
            index=models.Index(fields=['recipient_id', 'timestamp'], name='automation__recipie_2ee572_idx'),
        ),
    ]
