# Generated by Django 4.2.24 on 2026-01-02 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation_app', '0040_passwordresetotp_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetotp',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='passwordresetotp',
            name='reset_token',
        ),
    ]
